fruits=('olma','anor','nok')
print(type(fruits))
print(fruits)
print(fruits[2])
fruits1=list(fruits)
fruits1.insert(1,"shaftoli")
fruits1.append("gilos")
fruits=tuple(fruits1)
y=("qovun","tarvuz")
fruits+=y
print(type(fruits), fruits)